### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by stof** [comment]
I would allow failures on PHP 7 for now, given that it does not work yet (and you should probably enable PHP7 testing on guzzle first and make them pass, because the issue is currently an incompatibility in guzzle)

**Comment by TomasVotruba** [comment]
@stof Fixed

**Comment by fabpot** [comment]
Thank you @TomasVotruba.

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
