### PR TITLE
Updated doc to replace deprecated guzzle setDefaultOption method call

### PR DESCRIPTION
**Pull request by georaldc**
Added an updated example to achieve similar output.

### CODE REVIEW

**Comment by ssanders** [comment]
There should be examples for Goutte 3, 2, and 1, as they are so wildly different somehow.

Though everyone hated when I tried adding one for Goutte 1 which people still actually use.

The existing one is for 2.

Actually it would probably be best if those who need cURL options just used Guzzle and DomCrawler, which would defeat the whole point of Goutte.

**Comment by georaldc** [comment]
Maybe I should have worded it out that the example was for the latest version (though I did semi-hint that with the Guzzle 6 reference)?

I don't know but I IMO think that the readme file should only pertain to the latest version to prevent confusion

**Comment by georaldc** [comment]
You can also view each tagged release's corresponding readme file so there's that if you need info on past releases.

**Comment by themagnifico** [comment]
+1

**Comment by OGProgrammer** [comment]
+1 had problems with readme, this mr helped

**Comment by project707** [comment]
How does this work when you need to do this in multiple places to the same instance throughout a class/service? I don't _think_ you can modify the new GuzzleClient instance after it is first instantiated, right?

**Comment by fabpot** [comment]
Thank you @georaldc.

**Pull request merged**
